version: '3'
services:
  syslog-ng-server:
    container_name: syslog-ng-server
    build: .
    ports:
      - "514:514"
      - "601:601"
      - "6514:6514"
    volumes:
      - "./syslog-ng-server/logs:/var/log/syslog-ng"
      - "./syslog-ng-server/socket:/var/run/syslog-ng"
      - "./syslog-ng-server/config/:/etc/syslog-ng"
  syslog-ng-client:
    container_name: syslog-ng-client
    build:
      context: .
      dockerfile: Dockerfile-client
    volumes:
      - "./syslog-ng-client/logs:/var/log/syslog-ng"
      - "./syslog-ng-client/socket:/var/run/syslog-ng"
      - "./syslog-ng-client/config/:/etc/syslog-ng"